### ISSUE TITLE
Infografia Actividad 2             1 "B" Kevin osorio aparicio

### ISSUE THREAD

**Issue by KevinOsorio23143** [SistemasTecTlaxiaco/actividad-2-infografia-KevinOsorio23143#1]
[Infografia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-KevinOsorio23143/files/9448779/Infografia.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica, has obtenido un 17.4% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
